# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)" 

# Use custom format
format = """
[┌───────────────────](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) """
